/**
 * x402 `batch-settlement` on Solana, against fixtures generated by the
 * payment-channels program's OWN codama client (`clients/typescript` at
 * solana-foundation/payment-channels `3ffa4d67`, driven by `@solana/kit`) —
 * `getOpenInstructionAsync`, `findEventAuthorityPda`, `getVoucherArgsEncoder`
 * and `getChannelEncoder`, with every key an ed25519 key from a seed of
 * `fill(n)`. So what is asserted is agreement with the program's own client,
 * not with this repository's reading of the Rust.
 */

import { describe, it, expect } from 'vitest';
import { ed25519 } from '@noble/curves/ed25519.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { base58Decode, base58Encode } from '../../utils/base58.js';
import { fromBase64 } from '../../utils/binary.js';
import { parseSolanaWireTransaction } from '../solana/wire-transaction.js';
import type { Signer } from '../solana/payment-channel.js';
import {
  PAYMENT_CHANNELS_PROGRAM_ID,
  buildSponsoredOpen,
  buildSvmBatchChannelConfig,
  buildSvmOpenInstruction,
  buildSvmTopUpInstruction,
  buildSvmVoucherMessage,
  decodeSvmBatchChannel,
  paymentChannelsEventAuthority,
  signSvmVoucher,
  singleRecipientDistributionHash,
  svmBatchChannelAddress,
  type BatchSettlementSvmOffer,
} from './svm.js';
import { ConfigError, ValidationError } from '../../client/errors.js';

function keypair(n: number): Signer & { address: string } {
  const privateKey = new Uint8Array(32).fill(n);
  const publicKey = ed25519.getPublicKey(privateKey);
  return { privateKey, publicKey, address: base58Encode(publicKey) };
}

const PAYER = keypair(1);
const SPONSOR = keypair(2);
const SESSION = keypair(3);
const RECEIVER = keypair(4);
const MINT = '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU';
const BLOCKHASH = 'EkSnNWid2cvwEVnVx9aBqawnmiCNiDgp3gUdkDPTKN1N';

const FIXTURE = {
  channel: 'WLNQ714q14a3SEXsbrXKDsWoxugYdGA6brPDGXpUWjX',
  eventAuthority: '75c2huVzDW1Eq4kD86by5392sjdJzuAT195XNgP2f2tX',
  openData:
    '012a0000000000000040420f0000000000805101000084d7170000000001000000ca93ac1705187071d67b83c7ff0efe8108e8ec4530575d7726879333dbdabe7c1027',
  // [address, role]: kit's AccountRole — 3 writable signer, 1 writable, 0 read-only.
  openAccounts: [
    ['AKnL4NNf3DGWZJS6cPknBuEGnVsV4A4m5tgebLHaRSZ9', 3],
    ['9hSR6S7WPtxmTojgo6GG3k4yDPecgJY292j7xrsUGWBu', 3],
    ['9hSR6S7WPtxmTojgo6GG3k4yDPecgJY292j7xrsUGWBu', 0],
    [MINT, 0],
    ['GyGKxMyg1p9SsHfm15MkNUu1u9TN2JtTspcdmrtGUdse', 0],
    ['WLNQ714q14a3SEXsbrXKDsWoxugYdGA6brPDGXpUWjX', 1],
    ['H1AviagU5Y17z77v1F9qZPJ9kCbCsL4ewiZABNfGYoRs', 1],
    ['3xXRTX2ximf6iSibzucxz9vCpasDse5e9uFwRNbvDzAX', 1],
    ['TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA', 0],
    ['11111111111111111111111111111111', 0],
    ['SysvarRent111111111111111111111111111111111', 0],
    ['ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL', 0],
    ['75c2huVzDW1Eq4kD86by5392sjdJzuAT195XNgP2f2tX', 0],
    ['CHNLxYvVA28MJP9PrFuDXccuoGXAx7jBacfLEkahyGsX', 0],
  ] as const,
  voucher1234:
    '56010783be761e96fcc2fe0b51b33cd691846f531b7511d3185afa63e34ca58c635ed2040000000000000000000000000000',
  // `getChannelEncoder` with discriminator 1 (the encoder leaves it to the caller):
  // status Closing, deposit 1_000_000, settled 1234, closureStartedAt 1_790_000_000.
  channelAccount:
    'AQH+AioAAAAAAAAAQEIPAAAAAADSBAAAAAAAAOgDAAAAAAAAgDuxagAAAAAAAAAAAAAAAIBRAQAJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCYqI4910CfGV/VLbLTy6XXLKZwm/HZQSG/N0iAG0D29cgTl3Dqh9F19Wo1Rmw0x+zMuNipG07jeiXfYPW4/Js5TtSSjGKNHCxurpAziQWZVhKVknOlxj+TY2wUYUrIc30TtELLORIVfxOpM9ATQoLQMrX/7NAaLb8bd5BgjfAC6ngTl3Dqh9F19Wo1Rmw0x+zMuNipG07jeiXfYPW4/Js5QAhNcXAAAAAA==',
};

const OFFER: BatchSettlementSvmOffer = {
  scheme: 'batch-settlement',
  network: 'solana:EtWTRABZaYq6iMfeYKouRu166VU2xqa1',
  amount: '1000',
  asset: MINT,
  payTo: RECEIVER.address,
  maxTimeoutSeconds: 300,
  extra: {
    feePayer: SPONSOR.address,
    withdrawDelay: 86_400,
    tokenProgram: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  },
};

const CONFIG = buildSvmBatchChannelConfig({
  payer: PAYER.address,
  payerAuthorizer: SESSION.address,
  offer: OFFER,
  salt: 42n,
  openSlot: 400_000_000n,
});

const hex = (b: Uint8Array) => Buffer.from(b).toString('hex');

describe('buildSvmBatchChannelConfig', () => {
  it('maps the offer onto the program seats x402 fixes (SVM spec §4.1)', () => {
    expect(CONFIG).toEqual({
      payer: PAYER.address,
      payerAuthorizer: SESSION.address,
      receiver: RECEIVER.address,
      token: MINT,
      withdrawDelay: 86_400,
      salt: 42n,
      openSlot: 400_000_000n,
    });
  });

  it('draws a random u64 salt when none is given', () => {
    const a = buildSvmBatchChannelConfig({
      payer: PAYER.address,
      offer: OFFER,
      openSlot: 1n,
    });
    const b = buildSvmBatchChannelConfig({
      payer: PAYER.address,
      offer: OFFER,
      openSlot: 1n,
    });
    expect(a.salt).not.toBe(b.salt);
    expect(a.salt < 2n ** 64n).toBe(true);
    expect(a.payerAuthorizer).toBe(PAYER.address);
  });

  it('refuses a payer or voucher signer that is the sponsor — the program needs payer ≠ payee', () => {
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: SPONSOR.address,
        offer: OFFER,
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        payerAuthorizer: SPONSOR.address,
        offer: OFFER,
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
  });

  it('refuses a grace period below the published minimum or outside x402’s 900s..30d', () => {
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        offer: OFFER,
        openSlot: 1n,
        withdrawDelay: 3_600,
      })
    ).toThrow(ConfigError);
    const tooShort = { ...OFFER, extra: { ...OFFER.extra, withdrawDelay: 60 } };
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        offer: tooShort,
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
  });

  it('refuses a grace period shorter than the offer’s maxTimeoutSeconds', () => {
    const slow = { ...OFFER, maxTimeoutSeconds: 2 * 86_400 };
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        offer: slow,
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
  });

  it('refuses a mint owned by a token program this client does not build for', () => {
    const token22 = {
      ...OFFER,
      extra: {
        ...OFFER.extra,
        tokenProgram: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb',
      },
    };
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        offer: token22,
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
  });

  it('refuses an offer on a network that is not Solana', () => {
    expect(() =>
      buildSvmBatchChannelConfig({
        payer: PAYER.address,
        offer: { ...OFFER, network: 'eip155:84532' },
        openSlot: 1n,
      })
    ).toThrow(ConfigError);
  });
});

describe('addresses', () => {
  it('derives the channel PDA from its seven seeds, as the program’s client does', () => {
    expect(svmBatchChannelAddress(CONFIG, SPONSOR.address)).toBe(
      FIXTURE.channel
    );
  });

  it('derives the event authority PDA', () => {
    expect(paymentChannelsEventAuthority()).toBe(FIXTURE.eventAuthority);
  });
});

describe('buildSvmOpenInstruction', () => {
  it('matches the program client’s open: data, and all 14 accounts in order', () => {
    const ix = buildSvmOpenInstruction({
      config: CONFIG,
      sponsor: SPONSOR.address,
      deposit: 1_000_000n,
    });
    expect(ix.programId).toBe(PAYMENT_CHANNELS_PROGRAM_ID);
    expect(hex(ix.data)).toBe(FIXTURE.openData);
    expect(
      ix.keys.map((k) => [
        k.pubkey,
        (k.isSigner ? 2 : 0) + (k.isWritable ? 1 : 0),
      ])
    ).toEqual(FIXTURE.openAccounts.map(([a, r]) => [a, r]));
  });

  it('refuses a zero deposit, which the program refuses', () => {
    expect(() =>
      buildSvmOpenInstruction({
        config: CONFIG,
        sponsor: SPONSOR.address,
        deposit: 0n,
      })
    ).toThrow(ValidationError);
  });
});

describe('buildSvmTopUpInstruction', () => {
  it('is discriminator 3 and the six accounts x402 names, with no sponsor among them', () => {
    const ix = buildSvmTopUpInstruction({
      config: CONFIG,
      sponsor: SPONSOR.address,
      amount: 5n,
    });
    expect(hex(ix.data)).toBe('030500000000000000');
    expect(ix.keys.map((k) => k.pubkey)).toEqual([
      PAYER.address,
      FIXTURE.channel,
      FIXTURE.openAccounts[6][0],
      FIXTURE.openAccounts[7][0],
      MINT,
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
    ]);
    expect(ix.keys[0]).toMatchObject({ isSigner: true, isWritable: true });
    expect(ix.keys.map((k) => k.pubkey)).not.toContain(SPONSOR.address);
  });
});

describe('vouchers', () => {
  it('is the 50-byte VoucherArgs the program’s client encodes', () => {
    expect(hex(buildSvmVoucherMessage(FIXTURE.channel, 1_234n))).toBe(
      FIXTURE.voucher1234
    );
  });

  it('always writes expires_at as zero (ADR 0074 decision 3)', () => {
    const message = buildSvmVoucherMessage(FIXTURE.channel, 1n);
    expect(hex(message.subarray(42))).toBe('00'.repeat(8));
  });

  it('refuses an amount outside u64', () => {
    expect(() => buildSvmVoucherMessage(FIXTURE.channel, 2n ** 64n)).toThrow(
      ValidationError
    );
    expect(() => buildSvmVoucherMessage(FIXTURE.channel, -1n)).toThrow(
      ValidationError
    );
  });

  it('signs with Ed25519 over exactly those 50 bytes, in x402’s BatchVoucher spelling', () => {
    const voucher = signSvmVoucher(SESSION, FIXTURE.channel, 1_234n);
    expect(voucher).toMatchObject({
      channelId: FIXTURE.channel,
      maxClaimableAmount: '1234',
      expiresAt: 0,
    });
    expect(
      ed25519.verify(
        base58Decode(voucher.signature),
        buildSvmVoucherMessage(FIXTURE.channel, 1_234n),
        SESSION.publicKey
      )
    ).toBe(true);
  });
});

describe('singleRecipientDistributionHash', () => {
  it('hashes the exact recipients preimage the program client puts in open', () => {
    // openArgs = salt(8) ‖ deposit(8) ‖ grace_period(4) ‖ open_slot(8) ‖ recipients;
    // the program stores sha256(recipients) as distribution_hash.
    const recipients = Buffer.from(FIXTURE.openData, 'hex').subarray(1 + 28);
    expect(hex(singleRecipientDistributionHash(RECEIVER.address))).toBe(
      hex(sha256(recipients))
    );
  });
});

describe('decodeSvmBatchChannel', () => {
  it('reads every field of the 256-byte channel account', () => {
    expect(decodeSvmBatchChannel(fromBase64(FIXTURE.channelAccount))).toEqual({
      status: 'closing',
      salt: 42n,
      deposit: 1_000_000n,
      settled: 1_234n,
      payoutWatermark: 1_000n,
      closureStartedAt: 1_790_000_000n,
      payerWithdrawnAt: 0n,
      gracePeriod: 86_400,
      distributionHash: new Uint8Array(32).fill(9),
      payer: PAYER.address,
      payee: SPONSOR.address,
      authorizedSigner: SESSION.address,
      mint: MINT,
      rentPayer: SPONSOR.address,
      openSlot: 400_000_000n,
    });
  });

  it('refuses bytes that are not a live channel account', () => {
    const bytes = fromBase64(FIXTURE.channelAccount);
    expect(() => decodeSvmBatchChannel(bytes.slice(0, 255))).toThrow();
    const tombstone = new Uint8Array(bytes);
    tombstone[0] = 2;
    expect(() => decodeSvmBatchChannel(tombstone)).toThrow();
  });
});

describe('buildSponsoredOpen', () => {
  const build = (sponsor = SPONSOR.address, memo?: string) =>
    buildSponsoredOpen({
      payer: PAYER,
      config: CONFIG,
      offer: OFFER,
      connectorSponsor: sponsor,
      deposit: 1_000_000n,
      recentBlockhash: BLOCKHASH,
      memo,
    });

  it('refuses any sponsor other than the receiving connector’s (ADR 0074 decision 5)', () => {
    expect(() => build(keypair(9).address)).toThrow(ConfigError);
  });

  it('is [open, memo], paid by the sponsor, signed by the payer, with the sponsor slot still empty', () => {
    const { transaction, channelId } = build();
    expect(channelId).toBe(FIXTURE.channel);

    const parsed = parseSolanaWireTransaction(transaction);
    expect(parsed.version).toBe('legacy');
    expect(parsed.recentBlockhash).toBe(BLOCKHASH);
    // Fee payer first; the only other required signer is the payer (SVM spec: signer set).
    expect(parsed.signers).toEqual([SPONSOR.address, PAYER.address]);
    expect(parsed.unsigned).toEqual([SPONSOR.address]);

    const bytes = fromBase64(transaction);
    const message = bytes.subarray(parsed.messageOffset);
    const payerSig = bytes.subarray(
      parsed.signaturesOffset + 64,
      parsed.signaturesOffset + 128
    );
    expect(ed25519.verify(payerSig, message, PAYER.publicKey)).toBe(true);
  });

  it('carries the offer’s memo when it has one, and a random hex nonce otherwise', () => {
    const withMemo = fromBase64(
      build(SPONSOR.address, 'invoice-123').transaction
    );
    expect(Buffer.from(withMemo).includes(Buffer.from('invoice-123'))).toBe(
      true
    );
    const a = build().transaction;
    const b = build().transaction;
    expect(a).not.toBe(b);
  });
});
